### ISSUE TITLE
Realizar saque

### ISSUE THREAD

**Issue by lucasdanillo** [SamuelSSan28/aula_github#3]
Descontar um determinado valor do saldo do cliente, verificando antes de fazer a operação se o valor especificado é maior ou igual ao saldo atual da conta do cliente.

**Comment by basilioarth** [comment]
Registrar essa operação na estrutura de dados responsável por armazenar todo o histórico de operações da conta (essa estrutura será utilizada no momento de obter o extrato da conta).
